### ISSUE TITLE
[TODO] Create special tiles

### ISSUE THREAD

**Issue by Bratah123** [KOOKIIEStudios/Califorknia#11]
**What needs to be done?**
A tile class that can trigger events, i.e. grass blocks that can initiate combat.
A tile that players aren't able to walk through
The tile class should also be rendered.

**Any other details? (optional)**
To start off, make the player walk over a tile, and print out some message stating "combat has initiated"

**Task breakdown (optional)**
- [x] Tile Class
- [x] Sprite attribute in class
- [ ] Hashmap that maps IDs to properties
- [ ] Give effect to properties (e.g. `non-traversable` property should disallow players from stepping on tile)
- [ ] A Wall (or any tile that a player shouldn't be able to cross like water)
- [ ] Grass Block (for meeting new dishes)
- [ ] Player triggers event
- [ ] Warp zone (e.g. doors to change map)
