### ISSUE TITLE
[TODO] Create placeholder background for testing purposes

### ISSUE THREAD

**Issue by KOOKIIEStudios** [KOOKIIEStudios/Califorknia#12]
**What needs to be done?**
Generate a bitmap with [WaveFunctionCollapse](https://github.com/mxgmn/WaveFunctionCollapse)

**When should this be done by? (optional)**
Next iteration

- [x] Refactor black screen to `World`
- [ ] Add bitmap to repo
- [ ] Add bitmap to `test_map` metadata
- [ ] Change black screen to render background image
- [x] Load background image dynamically from active map metadata

**Comment by KOOKIIEStudios** [comment]
WFC no longer needed due to a migration to tile-based system.
This has been implemented by @Bratah123 in bc233ae64da5d4cb99c2c1bf6c545ac390d84625
