### ISSUE TITLE
[TODO] `is_traversable` method for tiles

### ISSUE THREAD

**Issue by KOOKIIEStudios** [KOOKIIEStudios/Califorknia#15]
**What needs to be done?**
- [ ] A collection to store traversable IDs
- [ ] An `is_traversable(id: int) -> bool` method that takes in an entity/tile ID, and returns whether a player can walk on it
- [ ] Implement checks using the above method for whether a tile is traversable

**When should this be done by? (optional)**
Next iteration

**Any other details? (optional)**
Currently, the game overwrites the tile ID. This will be a problem in the future when we have multiple tile types with special attributes.

**Comment by KOOKIIEStudios** [comment]
Deprecated
