### ISSUE TITLE
[TODO] Make YAML loader

### ISSUE THREAD

**Issue by KOOKIIEStudios** [KOOKIIEStudios/Califorknia#17]
**What needs to be done?**
Write a wrapper for `ruamel.yaml`.

**When should this be done by? (optional)**
This iteration

**Task breakdown (optional)**
Use this if you need to break the task down into several smaller tasks
- [x] Write wrapper for load/dump of YAML documents
- [x] Refactor parts of `constants.py` to YAML (#8)
- [x] Refactor magic numbers to YAML after #19 is completed
- [x] Create map metadata YAML
